Web_App/Controllers/LoginController.cs
using Core.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using Web_App.Models;
using Web_App.Session;

using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace Web_App.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ITherapistRepository _therapistRepository;
        private readonly IPatientRepository _patientRepository;

        public LoginController(ILogger<LoginController> logger, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ITherapistRepository therapistRepository, IPatientRepository patientRepository)
        {
            _logger = logger;
            _userManager = userManager;
            _signInManager = signInManager;
            _therapistRepository = therapistRepository;
            _patientRepository = patientRepository;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            if (SessionState.IsUserConsent(HttpContext))
            {
                if (HttpContext.Session.GetBoolean("LoggedIn"))
                {
                    if (HttpContext.Session.GetBoolean("IsAdmin") || HttpContext.Session.GetBoolean("IsTherapist") || HttpContext.Session.GetBoolean("IsStudent"))
                        return RedirectToAction("Index", "Patient");
                    else if (HttpContext.Session.GetBoolean("IsPatient"))
                        return RedirectToAction("Index", "Profile");
                }
                return View();
            }
            return RedirectToAction("Privacy", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Index(LoginModel data)
        {
            if (SessionState.IsUserConsent(HttpContext))
            {
                if (ModelState.IsValid && !HttpContext.Session.GetBoolean("LoggedIn"))
                {
                    ApplicationUser identityUser = (await _userManager.FindByNameAsync(data.UserName)) as ApplicationUser;
                    if (identityUser != null)
                    {
                        SignInResult signInResult = await _signInManager.PasswordSignInAsync(identityUser, data.Password, false, false);
                        if (signInResult.Succeeded)
                        {
                            HttpContext.Session.SetObject("CurrentUser", identityUser);

                            bool isAdministrator = await _userManager.IsInRoleAsync(identityUser, Role.ADMINISTRATOR_ROLE);
                            bool isTherapist = await _userManager.IsInRoleAsync(identityUser, Role.THERAPIST_ROLE);
                            bool isStudent = await _userManager.IsInRoleAsync(identityUser, Role.STUDENTTHERAPIST_ROLE);
                            bool isPatient = await _userManager.IsInRoleAsync(identityUser, Role.PATIENT_ROLE);

                            HttpContext.Session.SetBoolean("IsAdmin", isAdministrator);
                            HttpContext.Session.SetBoolean("IsTherapist", isTherapist);
                            HttpContext.Session.SetBoolean("IsStudent", isStudent);
                            HttpContext.Session.SetBoolean("IsPatient", isPatient);

                            HttpContext.Session.SetBoolean("LoggedIn", true);
                            HttpContext.Session.SetObject("ProfilePictureBase64", "");

                            if (isAdministrator || isTherapist || isStudent)
                            {
                                Therapist therapistResult = _therapistRepository.Get(identityUser.DataId);
                                if (therapistResult != null)
                                {
                                    HttpContext.Session.SetObject("UserDataId", therapistResult.Id);
                                    HttpContext.Session.SetObject("ProfilePictureBase64", therapistResult.ProfilePictureBase64);
                                }

                                using (HttpClient http = new HttpClient())
                                {
                                    string url = $"https://sswf-api-pascal.azurewebsites.net";
                                    //string url = $"https://sswf-phrstoop-api.azurewebsites.net";
                                    //string url = $"https://localhost:44390";
                                    HttpContext.Session.SetObject("WebAPIHost", url);

                                    HttpResponseMessage webApiSignInResponse = await http.PostAsJsonAsync($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/auth/signin", new SignInRequest()
                                    {
                                        UserName = data.UserName,
                                        Password = data.Password
                                    });

                                    if (webApiSignInResponse.IsSuccessStatusCode)
                                    {
                                        string responseJson = await webApiSignInResponse.Content.ReadAsStringAsync();
                                        SignInResponse responseBody = JsonSerializer.Deserialize<SignInResponse>(responseJson);

                                        HttpContext.Session.SetBoolean("WebApiLoggedIn", true);
                                        HttpContext.Session.SetObject("WebApiToken", responseBody.token);
                                    }
                                    else
                                    {
                                        HttpContext.Session.SetBoolean("WebApiLoggedIn", false);
                                        HttpContext.Session.SetObject("WebApiToken", string.Empty);
                                    }
                                }
                                return RedirectToAction("Index", "Patient");
                            }
                            else if (isPatient)
                            {
                                Patient patientResult = _patientRepository.Get(identityUser.DataId);
                                if (patientResult != null)
                                {
                                    HttpContext.Session.SetObject("UserDataId", patientResult.Id);
                                    HttpContext.Session.SetObject("PatientNumber", patientResult.PatientNumber);
                                    HttpContext.Session.SetObject("ProfilePictureBase64", patientResult.ProfilePictureBase64);
                                }
                                return RedirectToAction("View", "Patient", new { pn = patientResult.PatientNumber, tabTo = "ed-tab" });
                            }
                            return RedirectToAction("Index");
                        }
                    }
                }
                return View(data);
            }
            return View(data);
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Logout()
        {
            if (SessionState.IsUserConsent(HttpContext))
            {
                if (HttpContext.Session.GetBoolean("LoggedIn"))
                {
                    _signInManager.SignOutAsync().Wait();

                    HttpContext.Session.SetBoolean("LoggedIn", false);
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

Web_App/Views/Shared/_Layout.cshtml
@using Web_App.Session;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_App</title>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/css/theme.css" />
    <link rel="stylesheet" href="~/scss/theme.scss" />
    <link rel="stylesheet" href="~/scss/_user-variables.scss" />
    <link rel="stylesheet" href="~/scss/_user.scss" />
</head>
<body>
    <header>
        @if (Context.Session.GetBoolean("LoggedIn"))
        {
        <nav class="navbar-classic navbar navbar-expand-lg">
            <ul class="navbar-nav navbar-left-wrap d-flex nav-top-wrap px-2">
                <li class="dropdown ms-2 nav-item">
                    <b><a class="nav-link" role="button" id="dropdownPatient" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</a></b>
                    <div class="dropdown-menu dropdown-menu-start" aria-labelledby="dropdownPatient">
                        @if (!Context.Session.GetBoolean("IsPatient"))
                        {
                            <h6 class="dropdown-header">Patients</h6>
                            <ul class="list-unstyled">
                                <li>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Patient">Overview</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-action="Add" asp-controller="Patient">Add Patient</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            string pn = Context.Session.GetObject<string>("PatientNumber");
                            <ul class="list-unstyled">
                                <li>
                                    <a class="dropdown-item" asp-action="View" asp-controller="Patient" asp-route-pn="@pn">Patient File</a>
                                </li>
                            </ul>
                            <ul class="list-unstyled">
                                <li>
                                    <b><a class="dropdown-item" asp-action="Index" asp-controller="Appointment" asp-route-pn="@pn">Appointments</a></b>
                                </li>
                            </ul>
                        }
                    </div>
                </li>
                @if (!Context.Session.GetBoolean("IsPatient"))
                {
                    @await Component.InvokeAsync("AppointmentCount")
                }
            </ul>
            <ul class="navbar-nav navbar-right-wrap ms-auto d-flex nav-top-wrap px-2">
                <li class="dropdown ms-2">
                    <a class="rounded-circle" href="#" role="button" id="dropdownUser" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="hstack gap-3">
                            <div class="avatar avatar-md avatar-indicators avatar-online">
                                @{
                                    string profilePictureBase64 = Context.Session.GetObject<string>("ProfilePictureBase64");
                                }
                                <img alt="avatar" src="data:image/png;base64, @profilePictureBase64" class="rounded-circle">
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownUser">
                        <div class="px-4 pb-0 pt-2">
                            <div class="lh-1 ">
                                <h5 class="mb-1 text-primary">@this.User.Identity.Name</h5>
                            </div>
                            <div class=" dropdown-divider mt-3 mb-2"></div>
                        </div>
                        <ul class="list-unstyled">
                            <li>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Profile">Profile</a>
                            </li>
                            <li>
                                <form asp-controller="Login" asp-action="Logout">
                                    <div class="form-group">
                                        <input type="submit" value="Log-out" class="dropdown-item text-dark-danger" />
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </nav>
        }
    </header>
    @{
        string containerStyle = Context.Session.GetBoolean("LoggedIn") ? "container site-content" : "container";
        string mainStyle = Context.Session.GetBoolean("LoggedIn") ? "pb-3 mt-6" : "";
    }
    <div class="@containerStyle">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="@mainStyle">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        &copy; 2021 - Web_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>