Web_App/Controllers/TreatmentController.cs
using Core.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Web_App.Models;
using Web_App.Session;

namespace Web_App.Controllers
{
    public class TreatmentController : Controller
    {
        private readonly ILogger<TreatmentController> _logger;
        private readonly ITreatmentRepository _treatmentRepository;
        private readonly IPatientRepository _patientRepository;
        public TreatmentController(ILogger<TreatmentController> logger, ITreatmentRepository treatmentRepository, IPatientRepository patientRepository)
        {
            _logger = logger;
            _treatmentRepository = treatmentRepository;
            _patientRepository = patientRepository;
        }

        [HttpGet]
        [Authorize(Roles = "Administrator,Therapist,Student")]
        [Route("/Treatment/Add/{tpid?}/{pn?}")]
        public async Task<IActionResult> Add(string tpid, string pn)
        {
            InfoModel infoModel = new InfoModel();
            int treatmentPlanId = -1;
            if (!string.IsNullOrEmpty(pn) && int.TryParse(tpid, out treatmentPlanId))
            {
                TreatmentModel treatmentModel = new TreatmentModel();
                treatmentModel.PatientName = _patientRepository.Get(pn).Name;
                treatmentModel.PatientNumber = pn;
                treatmentModel.TreatmentPlanId = treatmentPlanId;
                treatmentModel.AddedDate = DateTime.Now;
                treatmentModel.EndDate = DateTime.Now.AddDays(7);
                treatmentModel.TreatmentTypes = new List<TreatmentType>();

                if (!string.IsNullOrEmpty(HttpContext.Session.GetObject<string>("WebApiToken")))
                {
                    using (HttpClient http = new HttpClient())
                    {
                        http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetObject<string>("WebApiToken"));
                        treatmentModel.TreatmentTypes = await http.GetFromJsonAsync<List<TreatmentType>>($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/treatmenttypes");
                    }
                }
                return View(treatmentModel);
            }
            else
            {
                infoModel.TableEntries.Add("TPID Parameter: ", tpid);
                infoModel.TableEntries.Add("PN Parameter: ", pn);
            }
            infoModel.Title = "Add Treatment - Error";
            infoModel.Description = $"An error occurred while trying to view the Treatment";
            infoModel.Description += "\n, please contact the server admins to resolve this issue.";
            infoModel.HasImportantData = false;

            infoModel.ReturnAction = "Index";
            infoModel.ReturnController = "Patient";

            HttpContext.Session.SetObject("InfoEntries", infoModel.TableEntries);
            return RedirectToAction("Index", "Info", infoModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Therapist,Student")]
        [Route("/Treatment/Add/{tpid?}/{pn?}")]
        public async Task<IActionResult> Add(TreatmentModel treatmentModel, string tpid, string pn)
        {
            if (ModelState.IsValid)
            {
                Treatment forgedTreatment = treatmentModel.Forge();
                string token = HttpContext.Session.GetObject<string>("WebApiToken");
                if (!string.IsNullOrEmpty(token))
                {
                    if (token != "mocktoken")
                    {
                        using (HttpClient http = new HttpClient())
                        {
                            http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                            treatmentModel.TreatmentTypes = await http.GetFromJsonAsync<List<TreatmentType>>($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/treatmenttypes?code=" + forgedTreatment.VektisType);
                        }
                    }
                    if (treatmentModel.TreatmentTypes.Count() > 0)
                    {
                        if (treatmentModel.TreatmentTypes.FirstOrDefault(x => x.Code == forgedTreatment.VektisType).IsExplanationMandatory && string.IsNullOrEmpty(forgedTreatment.Particularities))
                            ModelState.AddModelError("Particularities", "Particularities is required for this Treatment Type");
                        else
                        {
                            (bool, Exception) addTreatmentResult = _treatmentRepository.AddTreatment(forgedTreatment);
                            if (addTreatmentResult.Item1)
                                return RedirectToAction("Edit", "Patient", new { pn = treatmentModel.PatientNumber, tabTo = "tmp-tab" });
                        }
                    }
                }
            } 
            else
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetObject<string>("WebApiToken")))
                {
                    using (HttpClient http = new HttpClient())
                    {
                        http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetObject<string>("WebApiToken"));
                        treatmentModel.TreatmentTypes = await http.GetFromJsonAsync<List<TreatmentType>>($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/treatmenttypes");
                    }
                }
            }
            treatmentModel.PatientName = _patientRepository.Get(pn).Name;
            return View(treatmentModel);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator,Therapist,Student")]
        [Route("/Treatment/Edit/{tid?}/{pn?}")]
        public async Task<IActionResult> Edit(string tid, string pn)
        {
            InfoModel infoModel = new InfoModel();
            int treatmentId = -1;
            if (!string.IsNullOrEmpty(pn) && int.TryParse(tid, out treatmentId))
            {
                Treatment treatment = _treatmentRepository.GetTreatment(treatmentId);
                if (treatment != null)
                {
                    TreatmentModel treatmentModel = TreatmentModel.Create(treatment, pn, _patientRepository.Get(pn).Name);
                    treatmentModel.PatientName = _patientRepository.Get(pn).Name;
                    treatmentModel.PatientNumber = pn;
                    treatmentModel.TreatmentTypes = new List<TreatmentType>();

                    if (!string.IsNullOrEmpty(HttpContext.Session.GetObject<string>("WebApiToken")))
                    {
                        using (HttpClient http = new HttpClient())
                        {
                            http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetObject<string>("WebApiToken"));
                            treatmentModel.TreatmentTypes = await http.GetFromJsonAsync<List<TreatmentType>>($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/treatmenttypes");
                        }
                    }
                    return View(treatmentModel);
                }
                infoModel.TableEntries.Add("Treatment Entity: ", treatment == null ? "Empty" : "Set");
            }
            else
            {
                infoModel.TableEntries.Add("TID Parameter: ", tid);
                infoModel.TableEntries.Add("PN Parameter: ", pn);
            }

            infoModel.Title = "Edit Treatment - Error";
            infoModel.Description = $"An error occurred while trying to view the Treatment";
            infoModel.Description += "\n, please contact the server admins to resolve this issue.";
            infoModel.HasImportantData = false;

            infoModel.ReturnAction = "Index";
            infoModel.ReturnController = "Patient";

            HttpContext.Session.SetObject("InfoEntries", infoModel.TableEntries);
            return RedirectToAction("Index", "Info", infoModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator,Therapist,Student")]
        [Route("/Treatment/Edit/{tid?}/{pn?}")]
        public async Task<IActionResult> Edit(TreatmentModel treatmentModel, string tid, string pn)
        {
            int treatmentId = -1;
            if (ModelState.IsValid && int.TryParse(tid, out treatmentId))
            {
                Treatment forgedTreatment = treatmentModel.Forge();
                forgedTreatment.Id = treatmentId;
                treatmentModel.Id = treatmentId;
                if (!string.IsNullOrEmpty(HttpContext.Session.GetObject<string>("WebApiToken")))
                {
                    using (HttpClient http = new HttpClient())
                    {
                        http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetObject<string>("WebApiToken"));
                        treatmentModel.TreatmentTypes = await http.GetFromJsonAsync<List<TreatmentType>>($"{HttpContext.Session.GetObject<string>("WebAPIHost")}/api/v1/treatmenttypes?code=" + forgedTreatment.VektisType);
                    }
                    if (treatmentModel.TreatmentTypes.Count() > 0)
                    {
                        if (treatmentModel.TreatmentTypes.FirstOrDefault(x => x.Code == forgedTreatment.VektisType).IsExplanationMandatory && string.IsNullOrEmpty(forgedTreatment.Particularities))
                            ModelState.AddModelError("Particularities", "Particularities is required for this Treatment Type");
                        else
                        {

Web_App/Views/Treatment/Add.cshtml
@model Web_App.Models.TreatmentModel

@{
    ViewData["Title"] = "Add Treatment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.AntiForgeryToken()

<head>
    <link rel="stylesheet" href="~/css/Treatment.css" />
</head>
<div class="narrow-content-edit margin-auto-left-right">
    <ol id="navTo" class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Patient">Patients</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a asp-action="Edit" asp-controller="Patient" asp-route-pn="@Model.PatientNumber" asp-route-tabTo="tmp-tab">@Model.PatientName</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Treatment</li>
    </ol>
    <hr />

    <h1>Add New Treatment</h1>
    <hr />
    <div class="row card pb-3">
        <div class="col-md-6">
            <form asp-action="Add" asp-controller="Treatment">
                <div class="row content-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="PatientNumber" class="control-label"></label>
                            <input asp-for="PatientNumber" class="form-control" readonly />
                            <span asp-validation-for="PatientNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TreatmentPlanId" class="control-label"></label>
                            <input asp-for="TreatmentPlanId" class="form-control" readonly />
                            <span asp-validation-for="TreatmentPlanId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VektisType" class="control-label"></label>
                            <select class="dropdown form-control" asp-for="VektisType">
                                @for (int i = 0; i < Model.TreatmentTypes.Count(); i++)
                                {
                                    string diagnoseText = $"{Model.TreatmentTypes.ElementAt(i).Code} - {Model.TreatmentTypes.ElementAt(i).IsExplanationMandatory} - {Model.TreatmentTypes.ElementAt(i).Description}";
                                    <option value="@Model.TreatmentTypes.ElementAt(i).Code">@diagnoseText</option>
                                }
                            </select>
                            <span asp-validation-for="VektisType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Particularities" class="control-label"></label>
                            <input asp-for="Particularities" class="form-control"placeholder="..." />
                            <span asp-validation-for="Particularities" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Room" class="control-label"></label>
                            <input asp-for="Room" class="form-control"placeholder="Type a room..." />
                            <span asp-validation-for="Room" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="AddedDate" class="control-label"></label>
                            <input asp-for="AddedDate" class="form-control" readonly/>
                            <span asp-validation-for="AddedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EndDate" class="control-label"></label>
                            <input asp-for="EndDate" class="form-control" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group row content-row">
                            <div class="col-md-6">
                                <input type="submit" value="Save" class="btn btn-primary btn-wide" />
                            </div>
                            <div class="col-md-6">
                                <a asp-action="Edit" asp-controller="Patient" asp-route-pn="@Model.PatientNumber" asp-route-tabTo="tmp-tab" class="btn btn-secondary btn-wide">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Web_App/Views/Treatment/Edit.cshtml
@model Web_App.Models.TreatmentModel

@{
    ViewData["Title"] = "Edit Treatment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.AntiForgeryToken()

<head>
    <link rel="stylesheet" href="~/css/Treatment.css" />
</head>
<div class="narrow-content-edit margin-auto-left-right">
    <ol id="navTo" class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Patient">Patients</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a asp-action="Edit" asp-controller="Patient" asp-route-pn="@Model.PatientNumber" asp-route-tabTo="tmp-tab">@Model.PatientName</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit Treatment</li>
    </ol>
    <hr />

    <h1>Edit Treatment - @Model.Id</h1>
    <hr />
    <div class="row card pb-3">
        <div class="col-md-6">
            <form asp-action="Edit" asp-controller="Treatment">
                <div class="row content-row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="PatientNumber" class="control-label"></label>
                            <input asp-for="PatientNumber" class="form-control" readonly />
                            <span asp-validation-for="PatientNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="TreatmentPlanId" class="control-label"></label>
                            <input asp-for="TreatmentPlanId" class="form-control" readonly />
                            <span asp-validation-for="TreatmentPlanId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="VektisType" class="control-label"></label>
                            <select class="dropdown form-control" asp-for="VektisType">
                                @for (int i = 0; i < Model.TreatmentTypes.Count(); i++)
                                {
                                    string diagnoseText = $"{Model.TreatmentTypes.ElementAt(i).Code} - {Model.TreatmentTypes.ElementAt(i).IsExplanationMandatory} - {Model.TreatmentTypes.ElementAt(i).Description}";
                                    if (Model.VektisType == Model.TreatmentTypes.ElementAt(i).Code)
                                    {
                                        <option value="@Model.TreatmentTypes.ElementAt(i).Code" selected>@diagnoseText</option>
                                    }
                                    else
                                    {
                                        <option value="@Model.TreatmentTypes.ElementAt(i).Code">@diagnoseText</option>
                                    }
                                }
                            </select>
                            <span asp-validation-for="VektisType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Particularities" class="control-label"></label>
                            <input asp-for="Particularities" class="form-control" placeholder="..." />
                            <span asp-validation-for="Particularities" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Room" class="control-label"></label>
                            <input asp-for="Room" class="form-control" placeholder="Type a room..." />
                            <span asp-validation-for="Room" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="AddedDate" class="control-label"></label>
                            <input asp-for="AddedDate" class="form-control" readonly />
                            <span asp-validation-for="AddedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EndDate" class="control-label"></label>
                            <input asp-for="EndDate" class="form-control" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="form-group row content-row">
                            <div class="col-md-6">
                                <input type="submit" value="Save" class="btn btn-primary btn-wide" />
                            </div>
                            <div class="col-md-6">
                                <a asp-action="Edit" asp-controller="Patient" asp-route-pn="@Model.PatientNumber" asp-route-tabTo="tmp-tab" class="btn btn-secondary btn-wide">Cancel</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <button data-toggle="modal" data-target="#delete-dialog" type="button" class="btn btn-danger btn-wide">Delete</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="delete-dialog" tabindex="1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4 class="align-text-center">Are you sure want to delete this Treatment?</h4>
            </div>
            <div class="modal-footer">
                <div class="row content-row stretch">
                    <div class="col-md-6">
                        <a asp-action="Delete" asp-controller="Treatment" asp-route-tid="@Model.Id" asp-route-pn="@Model.PatientNumber" value="Delete" class="btn btn-danger btn-wide">Yes</a>
                    </div>
                    <div class="col-md-6">
                        <button type="button" class="btn btn-secondary btn-wide" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>